### ISSUE TITLE
Todo List Cometh

### ISSUE THREAD

**Issue by vincentlg** [cometh-game/devcon-raffle#2]
**why fork?**
Use this system to distribute part of the EthCC tickets and bring some improvements / new features

**smart contract**
- [x] Use RANDAO to draw the raffle winners
- [x] Apply a discount to raffle winners (Merkle tree with address => discount) #1 

**dapp**
- [ ] Replace trufi tools dependencies with Hardhat
- [ ] Develop the backend for the distribution of the voucher

**Docs**
https://raffle.devcon.org/
https://devcon.org/en/raffle-auction/
